#!/usr/bin/env Rscript

"pkr :: opinionated set of tools for working with R

Usage:
  pkr init
  pkr (in | install) ([<inpkg>...] | [--file=<pkr-file>]) [--global]
  pkr (rm | remove) <rmpkg>... [--global]
  pkr status
  pkr clean
  pkr test
  pkr lint
  pkr script (in | install) <script>
  pkr script (ls | list) <script>
  pkr script (rm | remove) <script>
  pkr script new <script>
  pkr -h | --help
  pkr -v | --version

Arguments:
  init             Initialize packrat project
  in, install      Install packages / scripts
  rm, remove       Remove packages / scripts
  ls, list         List installed scripts
  status           Show installed packages
  clean            Remove unused packages
  test             Run tests
  lint             Lint *.R files
  script           Work with Rscripts

Options:
  --global         Use global package installation location
  -h --help        Print this help
  -v --version     Show version number" -> doc

## Don't bug me!
default_mirror <- "http://cran.us.r-project.org"
pkr_bin_path <- "~/.pkr/bin"

#' Check if in a packrat project, exit if not
#' Turn on packrat mode
check_packrat <- function() {
  if (!file.exists("./packrat")) {
    stop("Not in a packrat project. Run `pkr init` first.")
  } else {
    packrat::on()
  }
}

#' Check if package_id is installed
installed_p <- function(package_id) {
  splits <- strsplit(package_id, "/")[[1]]
  name <- if (length(splits) == 1) package_id else splits[2]
  require(name, character.only = TRUE)
}

#' Install package given as pkr style package id
install <- function(package_id) {
  splits <- strsplit(package_id, "/")[[1]]

  if (length(splits) == 1) {
    ## This is plain CRAN package
    install.packages(package_id, repos = default_mirror)
  } else if (length(splits) == 2) {
    ## gh package of type user/repo
    devtools::install_github(package_id)
  } else {
    ## gh package of type user/repo/sub/dir
    devtools::install_github(
                paste(splits[1:2], collapse = "/"),
                subdir = paste(splits[3:length(splits)], collapse = "/")
              )
  }
}

#' Install package if not found
check_and_install <- function(package_id) {
  if (!installed_p(package_id)) {
    cat(paste0(package_id, " not found. Installing...\n"))
    install(package_id)
  }
}

#' Get package ids from a file (allows # style comments)
read_package_ids_from_file <- function(file_name) {
  lines <- readLines(file_name)
  Filter(function(x) (length(x) == 0) || (!startsWith(x, "#")), lines)
}

#' Initialize packrat repo with speed-ish settings
init_packrat <- function() {
  packrat::set_opts(vcs.ignore.src = TRUE)
  packrat::set_opts(use.cache = TRUE)
  packrat::init()
}

#' Setup bin directory for scripts
setup_pkr_bin <- function(pkr_bin = pkr_bin_path) {
  if (!dir.exists(pkr_bin)) {
    cat("Setting up pkr bin directory...\n")
    dir.create(pkr_bin, showWarnings = FALSE, recursive = TRUE)
    oldwd <- getwd()
    setwd(pkr_bin_path)
    init_packrat()
    setwd(oldwd)
  }
}

#' Setup self dependencies
self_setup <- function() {
  for (dep in c('docopt', 'packrat', 'devtools')) {
    if (!installed(dep)) {
      install(dep)
    }
  }
}

## Entry point
## Use globally installed docopt
packrat::off()
self_setup()
opts <- docopt::docopt(doc, version = "v0.3.0")

if (opts[["init"]]) {
  ## Run packrat init
  init_packrat()
  ## Install devtools locally for github packages
  check_and_install("devtools")

} else if (opts[["in"]] | opts[["install"]]) {
  if(length(opts[["--file"]]) == 1) {
    to_install <- read_package_ids_from_file(opts[["--file"]])
  } else {
    to_install <- opts[["<inpkg>"]]
  }

  ## Install given packages
  if (opts[["--global"]]) {
    packrat::off()
    cat("Using global path\n")
    if (length(to_install) == 0) {
      stop("Provide at least one package")
    }
  } else {
    check_packrat()
  }

  if (length(to_install) == 0) {
    init_packrat()
  } else {
    ## Packages to be installed from github
    github_indices <- sapply(to_install, function(p) {
      splits <- strsplit(p, "/")[[1]]
      return (length(splits) > 1)
    })

    for (github_package_id in to_install[github_indices]) {
      ## Install only if the package is not installed
      if (!installed_p(github_package_id)) {
        install(github_package_id)
      }
    }

    ## Install regular CRAN packages
    cran_indices <- !sapply(to_install[!github_indices], installed_p)
    sapply(to_install[!github_indices][cran_indices], install)
  }

 } else if (opts[["rm"]] | opts[["remove"]]) {
  if (opts[["--global"]]) {
    packrat::off()
    cat("Using global path\n")
  } else {
    check_packrat()
  }
  remove.packages(opts[["<rmpkg>"]])
} else if (opts[["status"]]) {
  check_packrat()
  packrat::status()
} else if (opts[["clean"]]) {
  check_packrat()
  packrat::clean()
} else if (opts[["lint"]]) {
  check_and_install("lintr")
  lintr::lint_package()
} else if (opts[["test"]]) {
  check_and_install("testthat")
  system("R CMD check")
} else if (opts[["create"]]) {
  name <- opts[["<script>"]]
  stub <- c(
    "#!/usr/bin/env Rscript",
    "",
    paste("\"usage:", name, "\" -> doc"),
    "",
    "opts <- docopt::docopt(doc)"
  )
  writeLines(stub, name)
} else if (opts[["save"]]) {
  ## Save the given script as an executable
  setup_pkr_bin()

  source_file <- opts[["<script>"]]
  script_name <- basename(source_file)
  target_file <- file.path(pkr_bin_path, script_name)
  file.copy(from = source_file, to = target_file, overwrite = TRUE)
  Sys.chmod(target_file, mode = "755")

  ## Create symlink for short name
  setwd(pkr_bin_path)
  short_name <- sub("^([^.]*).*", "\\1", script_name)
  if (!file.exists(short_name)) {
    file.symlink(source_file, short_name)
  }
  ## Install deps
  init_packrat()
}
